### ISSUE TITLE
Square not working

### ISSUE THREAD

**Issue by icehawk-de** [Ecodev/natural-gallery-typo3#29]
I use this extension with the thumbnail-format: square. But it don't work anymore. In 0.9.0 everything was fine, but in the 1.0.1 version the thumbnails are working only with natural-format.
I haven't found any additional settings to activate this?

Am I doing something wrong or is it a bug?

**Comment by sambaptista** [comment]
Hi, thanks for your report !

Are you having a natural layout while selecting a square layout ? If yes, same issue here, I add fix to my todo list.

If you observe something else, can you please provide more details ? thx.

**Comment by icehawk-de** [comment]
Yes. I have a natural layout and square layout is selected.

**Comment by sambaptista** [comment]
I've just released the v1.0.2 that corrects that behavior. 

Thank for your message.
