### ISSUE TITLE
[FEATURE REQUEST] TYPO3 8.7 compatible

### ISSUE THREAD

**Issue by JohannesDeml** [Ecodev/natural-gallery-typo3#30]
Are there any plans to make the plugin TYPO3 8.7 compatible? Or do you have any public roadmap I can take a look at? Great work so far :)

**Comment by sambaptista** [comment]
Hello, sorry for this delayed answer. 

Thank you for your positive input ! 

Unfortunately we have no developments planned at the moment. We'll probably upgrade for next TYPO3 8.x website that needs a gallery.

Best regards.

**Comment by fabarea** [comment]
Perhaps you could just test the extension by changing the typo3 compatibility in ext_emconf.php. It could well be that works like that. If not please, report the issue on this ticket and we will sort it out.

**Comment by SadlerJohnson** [comment]
I have installed NG into T3 v8.7.8. I had to ignore warnings to get it to install.  VHS and Media was required. The BE and FE partially work but not enough to display a gallery. The NG java-script makes it into the page with "naturalGallery.images =" seemingly populated but the gallery div is empty. This is with manually putting "file:1:/img/" into the Folders field which is interpreted as "/fileadmin/img" by the CMS but I haven't been able to get a Media collection to appear in the plugin BE.

My application is an image archive with around 2K images.  I'd like to be up-to-date with v8.7.8 to have some longevity but will have to move back to v7.6.23 if I can't get NG to work in that version.

**Comment by sambaptista** [comment]
@fabarea Any planned upgrade on an existing typo3 8.x that uses natural-gallery-typo3 ? Could be the opportunity to upgrade it as well.

**Comment by SadlerJohnson** [comment]
Hello again. I'm revisiting this with 8.7.16 and get a different (more interesting) result.  I still have to manually enter the Folder as above but this now generates data:

			`naturalGallery.images = [{&quot;thumbnail&quot;:&quot;\/fileadmin\/i\/p05a089.jpg&quot;,&quot;enlarged&quot;:&quot;\/fileadmin\/i\/p05a089.jpg&quot;,&quot;id&quot;:26709,&quot;title&quot;:null,&quot;description&quot;:null,&quot;tWidth&quot;:400,&quot;tHeight&quot;:261,&quot;eWidth&quot;:400,&quot;eHeight&quot;:261,&quot;categories&quot;:[]},`

Which seems that it is just the quote marks that aren't being interpreted correctly. Looks to be much closer to working than last time - but how much closer? Any hints?

**Comment by SadlerJohnson** [comment]
Although the images are working with above change the captions/titles aren't displaying in the gallery or the lightbox.  I've been digging around haven't been so lucky finding out why the metadata values are null in the generated HTML.

{"thumbnail":"\/fileadmin\/i\/germany\/psa3016_page%2015%2817%29.jpg","enlarged":"\/fileadmin\/i\/germany\/psa3016_page%2015%2817%29.jpg","id":"32684","title":null,"description":null,"tWidth":1080,"tHeight":1559,"eWidth":1080,"eHeight":1559,"categories":[]}

Some assistance would be very much appreciated.
