### ISSUE TITLE
HTML in titles

### ISSUE THREAD

**Issue by SadlerJohnson** [Ecodev/natural-gallery-typo3#31]
Hi,

If I add a link anchor to the title through metadata, the HTML link is displayed as text (<a href...) but the lightbox view displays the link properly. Is there anything to be done to allow the gallery render the links?

Thanks
Sadler

**Comment by sambaptista** [comment]
Hello !

This feature is not directly related to this repository, but rather the one of natural-gallery-js here : https://github.com/Ecodev/natural-gallery-js

I'm I right if I say our purpose is the following :  a click on the picture opens the lightbox and a click on the label redirects to your link ?

This behavior is actually not possible by natural-gallery-js. We have to upgrade the core and it has to be implemented carefully due the insertion of html we don't control. 

If it's a feature you really want/need create an issue on natural-gallery-js repo and we'll evaluate it.

**Comment by sambaptista** [comment]
Your request feature has been added. More details here : https://github.com/Ecodev/natural-gallery-js/issues/1
